import Api from "@/src/utils/api";
import List from "../../../../components/List";
import { TimeType } from "../../../layout";

export const dynamic = 'error';
export const dynamicParams = true;

export async function generateStaticParams() {
    return [{ slug: '1' }, { slug: '2' }, { slug: '3' }];
}

export default async function Page({ params }: { params: { slug: string; } }) {
    const data = await Api.get<TimeType>('http://worldtimeapi.org/api/timezone/Asia/Shanghai');
    const { slug } = params;
    return (
        <List
            data={data}
            items={[
                <>
                    You can opt back into dynamically rendering pages for dynamic params not generated by <code>generateStaticParams</code> by manually setting <code>dynamicParams = true</code>.
                </>,
                <>
                    dynamic page is {slug}
                </>,
            ]}
        />
    );
}